### ISSUE TITLE
Update README.md installation instructions to point to the latest release of this mod instead of version 1.0

### ISSUE THREAD

**Issue by BlueCyro** [CatSharkShin/KeepGlobalTransformToggle#1]
I just had a person use the installation instructions with the provided hyperlink to version 1.0 of this mod instead of the latest. I would highly recommend updating this as version 1.0 is very invasive to other peoples' inspectors in the world.

**Comment by CatSharkShin** [comment]
Thank you,
fixed in [c618737](https://github.com/CatSharkShin/KeepGlobalTransformToggle/commit/c6187376ff3acf5abf6b35c2a2616c5a7593adbf)
