### ISSUE TITLE
Mod leaves behind DynamicVariableSpaces

### ISSUE THREAD

**Issue by XDelta** [CatSharkShin/KeepGlobalTransformToggle#2]
Found a few in a world that were left behind by someone using the mod. I'd like for the mod to either not use DynamicVariableSpaces or atleast make sure to mark the DynamicVariableSpace as non-persistent so it doesn't get saved with the world.
https://github.com/CatSharkShin/KeepGlobalTransformToggle/blob/master/KeepGlobalTransformToggle.cs#L61

**Comment by CatSharkShin** [comment]
I set persistent to false in [8f10b88](https://github.com/CatSharkShin/KeepGlobalTransformToggle/commit/8f10b88c987b961f3ff77fbb02aab28bcecbd244)
