### ISSUE TITLE
Mod breaks some worlds

### ISSUE THREAD

**Issue by kazu0617** [CatSharkShin/KeepGlobalTransformToggle#3]
This mod add DynamicVariableSpace in userRoot, but some world doesn't think about this mechanism (it's like add DVS in Root with non-directly binding).

so, turn on `DirectlyBinding` in this area. 
https://github.com/CatSharkShin/KeepGlobalTransformToggle/blob/c6187376ff3acf5abf6b35c2a2616c5a7593adbf/KeepGlobalTransformToggle.cs#L59-L64

**Comment by kazu0617** [comment]
It break my world.

**Comment by CatSharkShin** [comment]
I set OnlyDirectBinding to true in [8f10b88](https://github.com/CatSharkShin/KeepGlobalTransformToggle/commit/8f10b88c987b961f3ff77fbb02aab28bcecbd244)

**Comment by CatSharkShin** [comment]
I set OnlyDirectBinding to true in [8f10b88](https://github.com/CatSharkShin/KeepGlobalTransformToggle/commit/8f10b88c987b961f3ff77fbb02aab28bcecbd244)
